title: Topher Hunt
email: hunt.topher@gmail.com
description: >
  Topher Hunt's personal site — blog, projects, and reference cheat sheets.
baseurl: ""
url: "https://topherhunt.github.io"
github_username: topherhunt

# Build settings
source: source
markdown: kramdown
